import type { Metadata } from "next";
import { Bricolage_Grotesque, Caveat, Manrope } from "next/font/google";
import ClientWrapper from "./ui/client-wrapper";
import { LanguageProvider } from "./ui/language-context";
import SiteNavbar from "./ui/site-navbar";
import "./globals.css";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-family",
  subsets: ["latin"],
  display: "swap",
});

const manrope = Manrope({
  variable: "--font-manrope-family",
  subsets: ["latin"],
  display: "swap",
});

const caveat = Caveat({
  variable: "--font-caveat-family",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Öpixxel Agency",
  description: "Generated by Öpixxel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} ${manrope.variable} ${caveat.variable} h-full antialiased overflow-x-clip`}
    >
      <body className="min-h-full flex flex-col overflow-x-clip">
        <ClientWrapper>
          <LanguageProvider>
            <SiteNavbar />
            {children}
          </LanguageProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
